const mongoose = require('mongoose');
require('dotenv').config();
const schema=new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    username:{
        type:String,
        required:true,
        unique:true
    },
    email:{
        type:String,
        required:true,
        unique:true
    },
    phone:{
        type:String,
        required:true,
        unique:true
    },
    password:{
        type:String,
        required:true
    },
    avatar:{
        type:String,
        default:'https://example.com/default-avatar.png'
    },
    status:{
        type:String,
        default:'Hey there! I am using Chat Application.'
    },
    chats:{
        type:[mongoose.Schema.Types.ObjectId],
        ref:'Chat',
        default:[]
    },
    lastSeen:{
        type:Date,
        default:Date.now
    },
    isOnline:{
        type:Boolean,
        default:false
    }
});
module.exports=mongoose.model('User',schema);